<?php
namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('states')->delete();

        $states = [ 'KALANGALA', 'KAMPALA', 'KIBOGA', 'LUWERO', 'MASAKA', 'MPIGI', 'MUBENDE', 'MUKONO', 'NAKASONGOLA', 'RAKAI', 'SSEMBABULE', 'KAYUNGA', 'WAKISO', 'LYANTONDE', 'MITYANA', 'NAKASEKE', 'BUIKWE', 'BUKOMANSIMBI', 'BUTAMBALA', 'BUVUMA', 'GOMBA', 'KALUNGU', 'KYANKWANZI', 'LWENGO', 'KYOTERA', 'KASSANDA', 'MASAKA CITY', 'BUGIRI', 'BUSIA', 'IGANGA', 'JINJA', 'KAMULI', 'KAPCHORWA', 'KATAKWI', 'KUMI', 'MBALE', 'PALLISA', 'SOROTI', 'TORORO', 'KABERAMAIDO', 'MAYUGE', 'SIRONKO', 'AMURIA', 'BUDAKA', 'BUDUDA', 'BUKEDEA', 'BUKWO', 'BUTALEJA', 'KALIRO', 'MANAFWA', 'MANFWA', 'NAMUTUMBA', 'BULAMBULI', 'BUYENDE', 'KIBUKU', 'KWEEN', 'LUUKA', 'NAMAYINGO', 'NGORA', 'SERERE', 'BUTEBO', 'NAMISINDWA', 'BUGWERI', 'KAPELEBYONG', 'KALAKI', 'JINJA CITY', 'MBALE CITY', 'SOROTI CITY', 'ADJUMANI', 'APAC', 'ARUA', 'GULU', 'KITGUM', 'KOTIDO', 'LIRA', 'MOROTO', 'MOYO', 'NEBBI', 'NAKAPIRIPIRIT', 'PADER', 'YUMBE', 'ABIM', 'AMOLATAR', 'AMURU', 'DOKOLO', 'KAABONG', 'KOBOKO', 'MARACHA', 'OYAM', 'AGAGO', 'ALEBTONG', 'AMUDAT', 'KOLE', 'LAMWO', 'NAPAK', 'NWOYA', 'OTUKE', 'ZOMBO', 'OMORO', 'PAKWACH', 'KWANIA', 'NABILATUK', 'KARENGA', 'MADI-OKOLLO', 'OBONGI', 'ARUA', 'GULU', 'TEREGO', 'LIRA', 'BUNDIBUGYO', 'BUSHENYI', 'HOIMA', 'KABALE', 'KABAROLE', 'KASESE', 'KIBAALE', 'KISORO', 'MASINDI', 'MBARARA', 'NTUNGAMO', 'RUKUNGIRI', 'KAMWENGE', 'KANUNGU', 'KYENJOJO', 'BULIISA', 'IBANDA', 'ISINGIRO', 'KIRUHURA', 'BUHWEJU', 'KIRYANDONGO', 'KYEGEGWA', 'MITOOMA', 'NTOROKO', 'RUBIRIZI', 'SHEEMA', 'KAGADI', 'KAKUMIRO', 'RUBANDA', 'RUKIGA', 'BUNYANGABU', 'KIKUUBE', 'KAZO', 'KITAGWENDA', 'RWAMPARA', 'FORTPORTAL', 'MBARARA CITY', 'HOIMA CITY',
        ];

        foreach ($states as $state) {
            State::create(['name' => $state]);
        }
    }

}
