<?php
namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('states')->delete();

        $states = ["BUIKWE", "BUKOMANSIMBI", "BUTAMBALA", "BUVUMA", "GOMBA", "KALANGALA", "KALUNGU", "KAMPALA", "KASSANDA", "KAYUNGA", "KIBOGA", "KYANKWANZI", "KYOTERA", "LUWERO", "LWENGO", "LYANTONDE", "MASAKA", "MASAKA CITY", "MITYANA", "MPIGI", "MUBENDE", "MUKONO", "NAKASEKE", "NAKASONGOLA", "RAKAI", "SSEMBABULE", "SSEMBABULE", "SSMBABULE", "WAKISO", "KWEEN", "AMURIA", "BUDAKA", "BUDUDA", "BUGIRI", "BUGWERI", "BUKEDEA", "BUKWO", "BULAMBULI", "BUSIA", "BUTALEJA", "BUTEBO", "BUYENDE", "IGANGA", "JINJA", "JINJA CITY", "KABERAMAIDO", "KALAKI", "KALIRO", "KAMULI", "KAPCHORWA", "KAPELEBYONG", "KATAKWI", "KEEN", "KIBUKU", "KUMI", "KWEEN", "LUUKA", "MANAFWA", "MANFWA", "MAYUGE", "MBALE", "MBALE CITY", "MBALW", "NAMAYINGO", "NAMISINDWA", "NAMUTUMBA", "NGORA", "PALLISA", "SERERE", "SIRONKO", "SOROTI", "SOROTI CITY", "TORORO", "ABIM", "ADJUMANI", "AGAGO", "ALEBTONG", "AMOLATAR", "AMUDAT", "AMURU", "APAC", "ARUA", "ARUA CITY", "DOKOLO", "GULU", "GULU CITY", "KAABONG", "KARENGA", "KITGUM", "KOBOKO", "KOLE", "KOTIDO", "KWANIA", "LAMWO", "LIRA", "LIRA CITY", "MADI-OKOLLO", "MARACHA", "MOROTO", "MOYO", "NABILATUK", "NAKAPIRIPIRIT", "NAPAK", "NEBBI", "NWOYA", "OBONGI", "OMORO", "OTUKE", "OYAM", "PADER", "PAKWACH", "TEREGO", "YUMBE", "ZOMBO", "BUHWEJU", "BULIISA", "BUNDIBUGYO", "BUNYANGABU", "BUSHENYI", "FORTPORTAL CITY", "HOIMA", "HOIMA CITY", "IBANDA", "ISINGIRO", "KABALE", "KABAROLE", "KAGADI", "KAKUMIRO", "KAMWENGE", "KANUNGU", "KASESE", "KAZO", "KIBAALE", "KIKUUBE", "KIRUHURA", "KIRYANDONGO", "KISORO", "KITAGWENDA", "KYEGEGWA", "KYENJOJO", "MASINDI", "MBARARA", "MBARARA CITY", "MITOOMA", "NTOROKO", "NTUNGAMO", "RUBANDA", "RUBIRIZI", "RUKIGA", "RUKUNGIRI", "RWAMPARA", "SHEEMA"
        ];

        foreach ($states as $state) {
            State::create(['name' => $state]);
        }
    }

}
