services:

  # app:
  #   build:
  #     context: .docker rm -f laravel_postgres laravel_app laravel_nginx
  #     dockerfile: Dockerfile
  #   container_name: laravel_app
  #   volumes:
  #     - .:/var/www:z
  #   depends_on:
  #     - postgres

  app:
    image: lavsms:latest
    # container_name: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - postgres

 
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    image: postgres:14
    # container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: